#!/usr/bin/env bash
set -euo pipefail

if [[ $# == 0 ]]; then
  echo "Usage: create-script <file>"
  exit 1
fi

CUR_DIR=$(dirname $(readlink -f "$0"))
file=$CUR_DIR/$1
if [[ ! -e $file ]]; then
  template_file="$CUR_DIR/lib/template.sh"
  cp $template_file $file
fi

chmod +x $file
# git update-index --chmod=+x $file
editor $file
